/**
 * QuestionEditor Component
 * 
 * Design Philosophy: Minimalismo Aéreo Moderno
 * - Clean form for editing questions
 * - Support for 4 answer options
 * - Selection of correct answer
 */

import { useState } from "react";
import { Question } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Trash2 } from "lucide-react";

interface QuestionEditorProps {
  question?: Question;
  onSave: (question: Omit<Question, "id" | "wrongCount">) => void;
  onCancel: () => void;
}

export default function QuestionEditor({ question, onSave, onCancel }: QuestionEditorProps) {
  const [statement, setStatement] = useState(question?.statement || "");
  const [answers, setAnswers] = useState(
    question?.answers.map((a) => ({ text: a.text, isCorrect: a.isCorrect })) || [
      { text: "", isCorrect: false },
      { text: "", isCorrect: true },
      { text: "", isCorrect: false },
      { text: "", isCorrect: false },
    ]
  );
  const [explanation, setExplanation] = useState(question?.explanation || "");
  const [correctAnswerIndex, setCorrectAnswerIndex] = useState(
    answers.findIndex((a) => a.isCorrect)
  );

  const handleAnswerChange = (index: number, text: string) => {
    const newAnswers = [...answers];
    newAnswers[index].text = text;
    setAnswers(newAnswers);
  };

  const handleCorrectAnswerChange = (index: string) => {
    const idx = parseInt(index);
    setCorrectAnswerIndex(idx);
    const newAnswers = answers.map((a, i) => ({
      ...a,
      isCorrect: i === idx,
    }));
    setAnswers(newAnswers);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!statement.trim()) {
      alert("Por favor, preencha o enunciado da pergunta");
      return;
    }

    if (answers.some((a) => !a.text.trim())) {
      alert("Por favor, preencha todas as opções de resposta");
      return;
    }

    if (!explanation.trim()) {
      alert("Por favor, preencha a explicação");
      return;
    }

    onSave({
      statement: statement.trim(),
      answers: answers.map((a) => ({
        id: "", // Will be generated by parent
        text: a.text.trim(),
        isCorrect: a.isCorrect,
      })),
      explanation: explanation.trim(),
    });
  };

  return (
    <Card className="border-border bg-white">
      <CardHeader>
        <CardTitle>{question ? "Editar Pergunta" : "Nova Pergunta"}</CardTitle>
      </CardHeader>

      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Statement */}
          <div className="space-y-2">
            <Label htmlFor="statement">Enunciado da Pergunta</Label>
            <Textarea
              id="statement"
              placeholder="Digite o enunciado da pergunta..."
              value={statement}
              onChange={(e) => setStatement(e.target.value)}
              rows={3}
            />
          </div>

          {/* Answers */}
          <div className="space-y-4">
            <Label>Opções de Resposta</Label>
            <RadioGroup value={correctAnswerIndex.toString()} onValueChange={handleCorrectAnswerChange}>
              <div className="space-y-3">
                {answers.map((answer, index) => (
                  <div key={index} className="flex items-start gap-3 p-3 border border-border rounded-lg">
                    <RadioGroupItem
                      value={index.toString()}
                      id={`answer-${index}`}
                      className="mt-2"
                    />
                    <div className="flex-1">
                      <Input
                        placeholder={`Opção ${String.fromCharCode(65 + index)}`}
                        value={answer.text}
                        onChange={(e) => handleAnswerChange(index, e.target.value)}
                        className="border-border"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </RadioGroup>
          </div>

          {/* Explanation */}
          <div className="space-y-2">
            <Label htmlFor="explanation">Explicação da Resposta</Label>
            <Textarea
              id="explanation"
              placeholder="Explique por que essa é a resposta correta..."
              value={explanation}
              onChange={(e) => setExplanation(e.target.value)}
              rows={4}
            />
          </div>

          {/* Actions */}
          <div className="flex gap-3 justify-end pt-4 border-t border-border">
            <Button type="button" variant="outline" onClick={onCancel}>
              Cancelar
            </Button>
            <Button
              type="submit"
              className="bg-primary hover:bg-primary/90 text-primary-foreground"
            >
              {question ? "Atualizar" : "Criar"} Pergunta
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
